### ISSUE TITLE
Auf gehts!!! :)

### ISSUE THREAD

**Issue by mimquadrat** [ioBroker/ioBroker.wolf#1]
Hi Steffen,
hast sicher viel um die Ohren....
Machst du eigentlich aktuell was mit ScriptGUI für ioBroker?
VG Martin

**Comment by smiling-Jack** [comment]
nein noch nicht werde nach dem Wolf adapter damit anfangen habe nur leider
garde Privat ein paar Probleme :-(

Aber ich habe noch große Pläne für ScriptGUI

2015-05-24 19:42 GMT+02:00 mimquadrat <notifications@github.com>:
