### ISSUE TITLE
 wolf.0 	error	Socket error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by fastsonic** [ioBroker/ioBroker.wolf#114]
Hi, become every 2-4 Minits:

wolf.0 | 2023-10-27 15:30:43.865 | error | Socket error: Error: read ECONNRESET
-- | -- | -- | --

ISM8I Firmware 1.80
HW 1.0

**Comment by Apollon77** [comment]
Maybe "Restart" the wolf system? ;-) ECONNRESET means that the device it connects to has closed/reset the connection

**Comment by fastsonic** [comment]
Hi, the Device read every 30 Seconds all Datapoints . also after some restarts the Error repeats every  2-3 Minits. Maybe the Pull is hitting something

**Comment by franks06347** [comment]
Fehler tritt bei mir auch auf:
[iobroker.Wolf._LOG.2023-11-06.log](https://github.com/ioBroker/ioBroker.wolf/files/13266324/iobroker.Wolf._LOG.2023-11-06.log)

**Comment by fred0815** [comment]
Grundsätzlich werden Änderungen von der Wolff Anlage automatisch übertragen. Wie ist euer polling intervall eingestellt? alle 30 sekunden?

**Comment by franks06347** [comment]
Ich habe zum Feld "Polling Intervall" keine Doku gefunden.
Ich habe 30 eingetragen:

![grafik](https://github.com/ioBroker/ioBroker.wolf/assets/95623262/341eb296-7292-4ede-bc9b-2ba7b68b9ea2)

**Comment by fred0815** [comment]
Das "Polling Intervall" in sek. fragt alle Informationen vom ISM8i ab inkl. möglicher geänderter Konfigurationen der Anlage.
Daher reicht hier vollkommen 3600 Sekunden (jede Stunde) oder noch länger.... Damit sollte der ECONNECTRESET vom Tisch sein. Ich habe nicht einen....

**Comment by franks06347** [comment]
Hab das "Polling Intervall" auf 3600 eingestellt ... beobachte ... und melde mich.

**Comment by franks06347** [comment]
Moin,
seit dem ich das "Polling Intervall" auf 3600 eingestellt habe, tritt der Fehler nicht mehr auf.
Kann die Eingabe kleinerer Werte als 3600 unterbunden werden, damit der nächste nicht über diesen Fehler stolpert?

**Comment by fastsonic** [comment]
Auch von meiner Seite. nach dem Erhöhen des Wertes auf 3600 ist komplett Ruhe mit dem Reset.
Danke !
