### ISSUE TITLE
Version 1.2.0 does not create variables

### ISSUE THREAD

**Issue by LHBL2003** [ioBroker/ioBroker.wolf#18]
EN: I uninstalled the Wolf adapter. When uninstalling the adapter the variables were deleted properly. But when installing version 1.2.0 no variables are created.
All devices have the Auto check mark set.

DE: Ich habe den Wolf Adapter deinstalliert. Beim deinstallieren wurden die Variablen ordnungsgemäß gelöscht. Aber beim installieren der Version 1.2.0 werden keine Variablen erstellt.
Alle Geräte haben den Haken Auto gesetzt.

**Comment by RustyThePropellerHead** [comment]
I was welcomed home to a cold house tonight after upgrading to 1.2.0 earlier today, back running 1.1.0

After the upgrade the communication stopped, also tried deleting the adapter and installing again, then was the same issue as @LHBL2003 >> no devices found. 
I have not done a full autopsy as my priority was getting my house warm again.

1.2.0 should be rolled back until the bugs are fixed.

**Comment by Apollon77** [comment]
Problem still existing?
