### ISSUE TITLE
DPT_Switch in boolean mode didn't work correct

### ISSUE THREAD

**Issue by schweigel** [ioBroker/ioBroker.wolf#21]
In boolean mode the DPT_Switch can be read correct, but if the value is changed inside iobroker the value switched to "On" or "Off" instead of "true" or "false".
I have fixed it in my fork (https://github.com/schweigel/ioBroker.wolf) but I'm not sure how to merge only this change.

**Comment by Apollon77** [comment]
If you know what to change then do only this change Vis GitHub Web ui ( edit file and propose changes)

**Comment by schweigel** [comment]
Ok, I have done this. Now Pull requests are open.
