### ISSUE TITLE
CWL fehlt in der Main.js 149 Programmanwahl

### ISSUE THREAD

**Issue by Einklaus** [ioBroker/ioBroker.wolf#27]
Wenn ich die 149 ansteuer kommt es zum Error

wolf.1 | 2020-06-24 20:46:26.630 | error | (4296) uncaught exception: The "list[1]" argument must 			be an instance of Buffer or Uint8Array. Received type string ('e')

Habe in der Main.js gesehen das dort etwas fehlt. 
So sieht der Bereich ab Zeile 354 aus
`    } else if (name === 'Programmwahl Warmwasser') {
        if (data == 0 || data === 'Standby') {
            return [new Buffer('04', 'hex'), 'Standby'];
        }
        else if (data == 2 || data === 'Dauerbetrieb') {
            return [new Buffer('02', 'hex'), 'Dauerbetrieb'];
        } else {
            return [new Buffer('00', 'hex'), 'Automatikbetrieb'];
        }
    } else if (name === 'Programmwahl Mischer' || name === 'Programmwahl Heizkreis') {
        if (data == 0 || data === 'Standby') {
            return [new Buffer('02', 'hex'), 'Standby'];
        }

dort fehlt die Anwahl für die CWL (zwischen Warmwasser und Mischer||Heizkreis)

`    } else if (name === 'Programmwahl Warmwasser') {
        if (data == 0 || data === 'Standby') {
            return [new Buffer('04', 'hex'), 'Standby'];
        }
        else if (data == 2 || data === 'Dauerbetrieb') {
            return [new Buffer('02', 'hex'), 'Dauerbetrieb'];
        } else {
            return [new Buffer('00', 'hex'), 'Automatikbetrieb'];
        }
    }   else if (name === 'Programmwahl CWL') {
        if (data == 3 || data === 'Reduzierte Lüftung') {
            return [new Buffer('03', 'hex'), 'Reduzierte Lüftung'];
        }
        else if (data == 2 || data === 'Feuchteschutz') {
            return [new Buffer('02', 'hex'), 'Feuchteschutz'];
        } else if (data == 1 || data === 'Nennlüftung') {
            return [new Buffer('01', 'hex'), 'Nennlüftung'];
        }
		else {
            return [new Buffer('00', 'hex'), 'Intensivlüftung'];
        }		
    }	else if (name === 'Programmwahl Mischer' || name === 'Programmwahl Heizkreis') {
        if (data == 0 || data === 'Standby') {
            return [new Buffer('02', 'hex'), 'Standby'];
    

Wenn man die Zeilen ab 226 ebenfalls anpasst kann man die CWL super ansteuern`

aktuell............
`        } else if (datapoints[dp].name === 'Programmwahl CWL') {
            if (_data === 0) {
                return 'Automatikbetrieb';
            } else if (_data === 1) {
                return 'Nennlüftung';
            } else if (_data === 3) {
                return 'Reduzierte Lüftung';
            } else {
                throw '';
            }
        } else {
            throw '';
        }

    }
    else if (type === 'DPT_HVACMode') {`

meine geänderte Version
`} else if (datapoints[dp].name === 'Programmwahl CWL') {
            if (_data === 0) {
                return 'Intensivlüftung';
            } else if (_data === 1) {
                return 'Nennlüftung';
            } else if (_data === 3) {
                return 'Reduzierte Lüftung';
            } else if (_data == 2) {
                return 'Feuchteschutz';
            } else {
                throw '';
            }
        }
    }
    else if (type === 'DPT_HVACMode') {`

Man kann dann mit der 149 in Verbindung mit 153 und 158 4 Geschwindigkeiten der Lüftung steuern

Grüße Klaus

**Comment by pacco81** [comment]
Hi !

Bin gerade auch am ism8i und einer CWL-2.
Kannst du bitte deine komplette Main.js einstellen ?

Besten Dank und Gruß,
Sebastian
