### ISSUE TITLE
Some Datapoints are not updating, if I'm updating from v. 0.9.2 to 1.2.1

### ISSUE THREAD

**Issue by moonGbox** [ioBroker/ioBroker.wolf#29]
For instance DP 177 "Betriebsart" is not changing it's value on 1.2.1. If I'm going back to v. 0.9.2 its working proper. Are there any dependencies on node.js or something else?

**Comment by Einklaus** [comment]
Versuche mal bei den Objekten von Logikwert auf Zahl anzuändern. Bei mir ging es dann auch mit der 1.2.1. (Parameter 149)
Bei Logikwert hatte ich nur Warnungen/Fehler. Musst nur darauf achten das du auch mit einer Zahl den Parameter ansteuerst.
![cwl](https://user-images.githubusercontent.com/42099224/85674051-c9943500-b6c4-11ea-8fc8-9a6100a47fac.png)

**Comment by moonGbox** [comment]
Danke für den Tipp, ich fürchte aber, dass das in meinem Fall nicht hilft, da z.B. der DP 177, den ich als Beispiel angebracht habe, hat HVacContrMode als Rolle. Aus irgendeinem Grund werden bei mir nach dem Update diverse DP nicht mehr aktualisiert und behalten den bisherigen Wert. Daher ist es schwer festzustellen, welche Datenpunkte es genau betrifft.

**Comment by Streit187** [comment]
Versuch mal das Modul neu zu starten. Das löst meine Probleme mit fehlenden Daten immer. Auch nach z.B. einem Stromausfall. 
Auf den Reset Button direkt auf dem Modul drücken bis zwei Lampen leuchten.
