### ISSUE TITLE
Datenpunkte 67-79 - Mischermodul 1 werden nicht erkannt

### ISSUE THREAD

**Issue by JarlMorgennebel** [ioBroker/ioBroker.wolf#31]
Moin Moin,

ich nutze den Wolf Adapter 1.2.1 von GitHub mit meiner Wolf24.

Mein Fußbodenkreis ist etwas exotisch verbaut und hängt nicht mit dem Radiatorenheizkreis zusammen, sondern am MM1. Damit kann ich den DPT_HVACMode für Radiatoren und Fußboden getrennt zwischen Standby und Automatikbetrieb wechseln.

Leider fehlen die Datenpunkte 67-79 im Wolf Adapter, d.h. ich kann zwar die Radiatoren von IOBroker aus schalten, nicht jedoch die Fußbodenheizung.

[https://www.wolf.eu/fileadmin/Wolf_Profi/Downloads/Montage-Bedienungsanleitungen/Regelungen/Zubehoer/3064356_201611_ISM8i_Montage-u.Bedienungsanleitung.pdf] Seite 23.

Wie kann ich die fehlenden Datenpunkte nachtragen/erweitern?

Danke, -MN

**Comment by Lollo79** [comment]
wie sieht ihre Adapterkonfiguration im IoBroker aus, hier können Geräte bzw. Datenpunktbereiche ab & an Geschaltet werden.

**Comment by JarlMorgennebel** [comment]
Moin,

Im Adapter:

- Heizgeräte 1: AUTO, Name: Radiatoren
- Heizgeräte 2-4: Aus
- Bedienmodule 1: AUTO, Name: BM2
- Bedienmodule 2-4: Aus
- Mischmodule 1: AUTO, Name: Fussboden
- Mischmodule 2-4: Aus
- Kaskadenmodule 1-4: Aus
- Solarzelle 1: AUTO, Name: Solarwarmwasser
- Solarzelle 2-4: Aus
- Comfort-Wohnungs-Lüftung 1-4: Aus
- Split Luft/Wasser-Wärmepumpe 1-4: Aus

In den Objekten sehe ich in BM2 die Datenpunkte 59-64, aber es fehlen die drei für das MM1-Modul:

<img width="1644" alt="Bildschirmfoto 2021-04-25 um 20 12 57" src="https://user-images.githubusercontent.com/59556758/116004504-3fc63880-a603-11eb-996f-e5f523964bcf.png">

Danke!

**Comment by Lollo79** [comment]
![2021-04-25 20_36_57-Window](https://user-images.githubusercontent.com/82908779/116005172-0e9b3780-a606-11eb-81f0-e2fae92cd1aa.png)
Ich meine dieses Bild wenn hier bei Bedienmodule 2. das aus angehakt ist wird er diese DPs nicht auslesen.

**Comment by JarlMorgennebel** [comment]
Danke,


das hatte ich in der Textbeschreibung über dem Bild :)

Hier als Screenshot:

![Wolf](https://user-images.githubusercontent.com/59556758/116007493-4f984980-a610-11eb-8ccb-5b9e04a30fbc.png)

Danke

**Comment by Lollo79** [comment]
Servus, im zuge dieser Unterhaltung habe ich bei mir festgestellt das die einmalige Warmwasserladung (DP194) auch bei mir abhanden gekommen ist und bin jetzt wieder zurück auf die 1.1.0 
![2021-04-26 12_14_14-Window](https://user-images.githubusercontent.com/82908779/116066963-f4ef0400-a688-11eb-91fa-734f25fb22ed.png) und siehe da sie ist wieder da. Auch die Adapterkonfigurationsseite sieht anders aus ist da evtl. bei dem bearbeiten dieser Seite etwas schief gelaufen? 
![2021-04-26 12_15_15-Window](https://user-images.githubusercontent.com/82908779/116067227-3ed7ea00-a689-11eb-987f-27f27a77f51a.png)

**Comment by JarlMorgennebel** [comment]
Hmmm...

Ich kann im IOBroker nur die 1.2.1 installieren. Auf Github liegen auch nur noch die 1.2*-Releases. Wie komme ich an die alten Versionen?

Danke

**Comment by Lollo79** [comment]
Von hier über das Katzensymbol (händische Installation) https://github.com/RustyThePropellerHead/ioBroker.wolf

**Comment by JarlMorgennebel** [comment]
Danke,


habe jetzt probeweise die V 1.1.0 am laufen. Der Knopf in BM0 für die Warmwasseraufladung ist wieder da, die fehlenden Datenpunkte fehlen immer noch - d.h. die Profilauswahl für das Mischermodul 1, DP 69-79:

![Wolf 1 1 1](https://user-images.githubusercontent.com/59556758/116388708-66ab8700-a81c-11eb-9698-168acbd4a5df.PNG)

Danke für die Hilf

**Comment by Lollo79** [comment]
Hallo nochmal, 

Dann muss irgendetwas im Aufbau des Gesamtsystems nicht stimmen. Ich Fasse einmal zusammen du hast eine CGB-2 24kw > ein MM und als Steuerung des Ganzen ein BM-2. 
Am BM-2 hast du den direkten Heizkreis (Radiatoren) sollte so aussehen. 
![2021-04-28 22_10_10-Window](https://user-images.githubusercontent.com/82908779/116466359-aa2ee100-a86e-11eb-8899-b670506c97c8.png)
einen Mischerkreis (FBH) am Rädchen gedreht taucht dann dieses Bild auf. 
![2021-04-28 22_12_00-Window](https://user-images.githubusercontent.com/82908779/116466518-e104f700-a86e-11eb-8b0d-0f9f1c581aa1.png)
und evtl. noch ein Bild für Warmwasser. 
In der Parametrierung der CGB-2 steht der HG40 auf 2 ? 
Paramentrierung des Mischermoduls MI05 auf 3 ? 
Hydraulikschaltbild gibt es hier https://konfig.wolf.eu/hydraulik/resources/pdf/47-52-014-001.pdf

Wenn diese Vorrausetzungen alle erfüllt werden bin auch ich leider am Ende meiner Erfahrungen und weiß nicht warum die benötigten Datenpunkte nicht auftauchen. 

Grüße Silvio

**Comment by JarlMorgennebel** [comment]
Danke,

keine Änderung, die Datenpunkte fehlen weiterhin.

Danke, -MN
