### ISSUE TITLE
feature request: Datenpunkt: Leistung Heizkreispumpe

### ISSUE THREAD

**Issue by flwilk** [ioBroker/ioBroker.wolf#33]
Wäre es möglich die aktuelle Leistung der Umwälzpumpe abzufragen? Der Zustand wird ja bereits abgefragt.

**Comment by Einklaus** [comment]
Hallo,
es gibt nur die von Wolf vorgegeben Datenpunkte.
Du kannst diese auch in der Anleitung zur ISM8 nachlesen.
Laut meiner Kenntnisse sind Erweiterungen nicht möglich
