### ISSUE TITLE
WOLF ISM7

### ISSUE THREAD

**Issue by CarminKern** [ioBroker/ioBroker.wolf#35]
Hi, habe den Wolf ISM7 Adapter,

wie baue ich den zu diesem Kontakt auf? Ich kann ja nirgendwo die IP eingeben...
Allgemein wie funktioniert der Adapter und wie nutze ich Ihn ?

**Comment by Einklaus** [comment]
Die ISM7 funktioniert nicht, du brauchst die ISM8i

**Comment by CarminKern** [comment]
Das ist sehr Schade, danke für die schnelle Antwort.
