### ISSUE TITLE
Version 1.2.1 does not get data from ISM8i 

### ISSUE THREAD

**Issue by bullrandle** [ioBroker/ioBroker.wolf#36]
New ISM8i with FW 1.6 installed in BWL 
adapter version 1.2.1 installed, 
module indicates successful connection, 
adapter also shows all green
but no objects are created.

After stepping back to 1.2.0 objects appear and CWL and BWL can be controlled.

**Comment by heckmic** [comment]
Same probleme here. Look at: https://forum.iobroker.net/topic/39787/wolf-ism8i-adapter-l%C3%A4uft-seit-07-12-2020-nicht-mehr

**Comment by pacco81** [comment]
Bei mir auch: 
V1.2.1 Es werden **keine** Datenpunkte angelegt
V1.2.0 Es werden Datenpunkte angelegt

ism8i: HW-Version: 1.0  FW-Version: 1.70
Wolf CW-2 mit BM2
ibroker in Docker auf Synology: "hosts": [
      "version": "3.1.6",
  "node": "v12.18.3",
  "arch": "x64",
  "adapters": {
    "admin": {
      "version": "4.1.11",
