### ISSUE TITLE
kein Datenpunkte bzw Objekte werden eingelesen

### ISSUE THREAD

**Issue by Catweazle007** [ioBroker/ioBroker.wolf#39]
Wenn ich die Version 1.2.1 installiere werden keine Objekte angelegt.
Wenn ich die Version 1.2.0 installiere werden zwar Objekte angelegt aber nicht alle. z.B. mein Solarmodul erscheint überhaupt nicht !

**Comment by Streit187** [comment]
Versuch mal das Modul neu zu starten. Das löst meine Probleme mit fehlenden Daten immer. Auch nach z.B. einem Stromausfall. 
Auf den Reset Button direkt auf dem Modul drück bis zwei Lampen leuchten.
