### ISSUE TITLE
Can't parse DP : 149 - data: 0620f080001504000000f006009500010095030100 - length: 21

### ISSUE THREAD

**Issue by Einklaus** [ioBroker/ioBroker.wolf#4]
Hallo,

bei der CWL erscheint leider der oben genannte Fehler gefolgt von einr weiteren Serie an Fehlermeldungen
uncaught exception: The "list[1]" argument must be one of type Array, Buffer, or Uint8Array. Received type string. Unter anderem werden 

Versucht mit Node 8.X und 10.X mit einem Raspi und mit einem Windows Rechner

Gruss
Klaus

**Comment by Apollon77** [comment]
Please add full log as in Forum and also best Forum link please!

**Comment by Einklaus** [comment]
I've found some little mistakes. Unfortunately I couldn't get any further with the parameters 154,155,156,157,159,160,161,162.
(Wolf.js  Line177   "Programmwahl CWL" is wrong. New --> "Programm CWL")

Here are more info's:
https://forum.iobroker.net/viewtopic.php?f=20&t=1507&p=177945#p177945

**Comment by RustyThePropellerHead** [comment]
Please close this issue as it was corrected in the last Pull
