### ISSUE TITLE
[gelöst] Was triggern um Programm 1 x Warmwasser auszulösen?

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#41]
Hallo Zusammen,

vielen Dank für den Adapter! 
Mittlerweile funktioniert er einwandfrei (Heizung mit Wärmepumpe BWL-1S und Bedienmodul, mit Version 1.2).
Die Soll-Temperatur kann ich problemlos umstellen, nun würde ich gerne das Programm "1xWarmwasser" starten.
Hat jemand eine Idee was ich dafür antriggern muss damit das startet?

Danke und Gruß,

Claus

**Comment by Claus1985** [comment]
Habs hinbekommen dank der guten Doku von Wolf.
Ich musste einfach einen Datenpunkt im Bedienmodul hinzufügen (boolean mit der ID 194).
Wenn ich den nun auf true setze startet er das Programm 1 x Warmwasser.
![image](https://user-images.githubusercontent.com/69499563/113503520-c28f3280-9532-11eb-9dd3-986da6d2e5f7.png)

**Comment by kopierschnitte** [comment]
Cool! Aber welche Doku meinst Du?
Dachte immer, da wäre überhaupt nichts dokumentiert...

**Comment by Apollon77** [comment]
Würde kich auch interessieren. Also an sich ist die 194 in den Settings mit drin... was genau ust denn falsch bzw tut bicht bzw was genau muss geändert werden? Bitte mal mit neuester version versuchen ... 194 liegt in bm0 was aktiviert wird sobald eins der anderen bm* bereiche aktiv wird

**Comment by Claus1985** [comment]
Ja hab’s gesehen, in der neusten Version wird der Punkt automatisch erstellt. Vorher muss nur der alte objektivsten gelöscht werden. Doku: Die Bedienungsanleitung der Heizung 🙈😅 da steht das auf den letzten Seiten beschrieben welche Datenpunkte es gibt und was damit möglich ist (State/Funktion usw.)

**Comment by kopierschnitte** [comment]
Wird diese Option im Smartset-Portal auch angezeigt?
