### ISSUE TITLE
Fehlerhaft Math.round Funktion 

### ISSUE THREAD

**Issue by Lollo79** [ioBroker/ioBroker.wolf#42]
Kann im Code der main.js die Schrittweite die in der Bedienungsanleitung steht angepasst werden?
Hier wird die Math.round Funktion mit *2 ) /2 gemacht, für die Schrittweite von 0,5 wäre aber *10)/10 angebrachter. 

Auszug Bedienungsanleitung ISM8: 
IDs                        Datenpunkt          Einheit  Wertebereich Schrittweite
65 / 78 / 91 / 104 Sollwertkorrektur  K           -4K - +4K       0,5K
66 / 79 / 92 / 105 Sparfaktor             K            0K - 10K        0,5K

Codeauszug:
 } else if (type === 'DPT_Tempd' && name === 'Sollwertkorrektur') {
        val = Math.round(data * 2) / 2;
        if (val > 4) {
            val = 4
        }
        if (val < -4) {
            val = 4
        }
        return [enc.encodeDPT9(data), val];
    } else if (type === 'DPT_Tempd' && name === 'Sparfaktor') {
        val = Math.round(data * 2) / 2;
        if (val > 10) {
            val = 10
        }
        if (val < 0) {
            val = 0
        }
        return [enc.encodeDPT9(data), val];

Danke und MfG Silvio

**Comment by schweigel** [comment]
Hallo,

*2/2 passt, damit wird 0,5 als Schrittweite erreicht. Mit /10*10 würde man die Schrittweite 0,1 erreichen, welche aber nicht der Definition entspricht.

Grüße Matthias

**Comment by Lollo79** [comment]
Nochmal Hallo, 

Habe durch eigenrecherche herausgefunden das dies richtig ist, also Sorry für das "angebrachter". 

Aber mal zum eigentlichen Problem, Ich nutze die Sollwertkorrektur automatisiert um auf starke Temperaturstürze oder auch anstiege zu reagieren, jedoch funktionieren nur ganze Schritte um 1 bei Schritten um 0,5 kommt ein sehr großes Durcheinander zustande das z.B. der Heizkreis plötzlich auf -4 & der Mischerkreis seltsamerweise auf 0,4 steht was ja eigentlich nicht sein darf. 

Grüße Silvio

**Comment by Lollo79** [comment]
Neue Erkenntnisse zu dem Thema im IoBroker Forum gefunden. https://forum.iobroker.net/topic/31440/wolf-adapter-sollwertkorrektur-in-0-5er-schritten?_=1619967470092
