### ISSUE TITLE
Request Frequency

### ISSUE THREAD

**Issue by cracker0dks** [ioBroker/ioBroker.wolf#46]
Is it possible to change the request frequency so that the datapoints are read at least every 10mins ? 
Maybe trigger a readout of all values in an interval ?

This are my current readouts... as you can see "kesseltemp" has an current value. The  rest lags behind at least 20min
![image](https://user-images.githubusercontent.com/1816621/125991102-6723af13-b749-43dd-a938-a5b96b28559c.png)

Thanks

Edit: I know some of them already changed but are not requested / send to the iobroker yet.

**Comment by Apollon77** [comment]
Please Test GitHub version and provide feedback.

**Comment by cracker0dks** [comment]
sadly I have no system to test this on atm. Can test this next summer, but thats a little late I guess :(

**Comment by Apollon77** [comment]
Thne I release it ... it is off by default ... so lets see
