### ISSUE TITLE
No data points get created after installation with 1.2.1

### ISSUE THREAD

**Issue by mirage-111** [ioBroker/ioBroker.wolf#47]
Fresh installation with 1.2.1 but no DataPoints get created.
A hint from iobroker Forum was to use 1.2.0 but also with this Version no Data Points get created
![ISM8i](https://user-images.githubusercontent.com/55852325/126807141-c129871d-b6a7-46f7-bc49-7081de8c235b.jpg)

can you please help, thanks

**Comment by imod89** [comment]
I have the same issue! is there a solution existing?

**Comment by Apollon77** [comment]
Debug Log?

**Comment by imod89** [comment]
![image](https://user-images.githubusercontent.com/76962599/135388031-763c9877-1aa8-4dba-9121-f78a3f623d18.png)
Good morning, thanks for fast response! Here is a log after restarting my instance.
I didnt find a way to change or set ip adress?

**Comment by Apollon77** [comment]
Please provide log from GitHub version ... please make sure to not choose the own IP in admin but 0.0.0.0
