### ISSUE TITLE
Auslesen von Betriebsstunden

### ISSUE THREAD

**Issue by Franzformator** [ioBroker/ioBroker.wolf#49]
Hallo, 

ist es möglich mit diesem Modul die Betriebsstunden des Verdichters der Wärmepumpe auszulesen? Über die Weboberfläche kann ich diesen Wert ablesen, im IoBroker (Anbindung per ISM8) kann ich den Wert leider nicht finden. 

Um Belastung/Verschleiß der Pumpe zu dokumentieren, wäre dieser Wert sehr hilfreich.

Vielen Dank!

**Comment by Apollon77** [comment]
Which ID is it?

**Comment by Apollon77** [comment]
no response
