### ISSUE TITLE
ISM8i and IOBroker in two different networks with firewall in between

### ISSUE THREAD

**Issue by JarlMorgennebel** [ioBroker/ioBroker.wolf#52]
Dear,

I installed a firewall between my LAN (192.168.1.0/24) which includes the ISM8i module and my IOBroker (192.168.3.0/24).

ISM8i Network configuration has changed accordingly to the IOBroker address and a rule for port 12004 as shown on the ISM8i webinterface has been added.

However, there is no communication possible between both devices. What do I need to pass in the firewall to allow messages being exchanged?

Thanks, -JM

**Comment by Apollon77** [comment]
Whats the error on the device? In fact the adapter opens a server and listens for incoming connections. can you somehoe manually try to do a connection out of that special network?
