### ISSUE TITLE
Datenfelder / Variablen mit falschem Typ trotz Update auf neuste Version

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#53]
Hi Zusammen,

vielen Dank für die Updates des Adapters! Ich finde es klasse, dass er nochmal aktualisiert wurde!
Allerdings bekomme ich trotz Update auf die neuste Version 1.32 die Fehlermeldung, dass die Variablen nicht den richtigen
Typ zugeordnet haben. Muss ich dafür etwas ändern oder ist das im Adapter fix vorgesehen?

`
<html>
<body>

wolf.0 | 2021-09-01 12:30:31.602 | info | State value to set for "wolf.0.hg0.184" has to be type "state" but received type "number"
-- | -- | -- | --
wolf.0 | 2021-09-01 12:30:18.812 | info | State value to set for "wolf.0.bm1.54" has to be type "state" but received type "number"
wolf.0 | 2021-09-01 12:18:11.389 | info | State value to set for "wolf.0.hg0.184" has to be type "state" but received type "number"
wolf.0 | 2021-09-01 12:07:27.908 | info | State value to set for "wolf.0.hg0.191" has to be type "state" but received type "number"
wolf.0 | 2021-09-01 12:07:26.247 | info | State value to set for "wolf.0.hg0.190" has to be type "state" but received type "number"
wolf.0 | 2021-09-01 12:07:26.188 | info | State value to set for "wolf.0.hg0.188" has to be type "state" but received type "string"
wolf.0 | 2021-09-01 12:07:26.104 | info | State value to set for "wolf.0.hg0.189" has to be type "state" but received type "string"
wolf.0 | 2021-09-01 12:07:26.099 | info | State value to set for "wolf.0.hg0.188" has to be type "state" but received type "string"
wolf.0 | 2021-09-01 12:07:26.095 | info | State value to set for "wolf.0.hg0.187" has to be type "state" but received type "string"
wolf.0 | 2021-09-01 12:07:26.093 | info | State value to set for "wolf.0.hg0.186" has to be type "state" but received type "string"
wolf.0 | 2021-09-01 12:07:26.087 | info | State value to set for "wolf.0.hg0.185" has to be type "state" but received type "string"

</body>
</html>`

Danke und Gruß,

Claus

**Comment by Apollon77** [comment]
Bitte mal die Objekte die betroffen sind via Admin löschen. Fehler danach weg?

**Comment by Claus1985** [comment]
Hat funktioniert, danke für den Tipp. Erst alles gelöscht, dann Einstellungen nochmal speichern und schließen. Danach legt er die Objekte neu an. Skripte funktionieren danach wieder wie gehabt und es kommt keine Fehlermeldung mehr.
