### ISSUE TITLE
Werte werden in neuster Version nicht aktualisiert

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#54]
Hallo,

nachdem ich am 01.09. die neuste Version 1.32 installiert habe habe ich alle Objekte gelöscht und neu anlegen lassen.
Das hat super geklappt, allerdings habe ich gerade festgestellt, dass er seit dieser Zeit die Werte nicht mehr
aktualisiert hat. Die Werte sind alle samt noch vom 01.09..

Woran kann das liegen und was kann ich tun um das zu ändern?
Meldungen (Fehler/Warnung) werden im Protokoll keine angezeigt.

@GermanBluefox ich habe nun wieder v 1.20 installiert das funktioniert einwandfrei. Kannst Du ggf. Die Änderungen an dieser Version vornehmen? Dann hätten wir eine funktionierende Basis auf dem aktuellen Stand.

Danke und Gruß,

Claus

**Comment by GermanBluefox** [comment]
Wird da was in den Log geschrieben? Fehler?

**Comment by Claus1985** [comment]
Im normalen Log stand nichts aber ich kann das die Tage nochmal installieren und mit debug testen.

**Comment by Claus1985** [comment]
Mit der neusten Version 1.34 funktioniert das Aktualisieren der Werte wieder. Vielen Dank für die Mühe!
