### ISSUE TITLE
Can't parse DP : 149 - length: 21

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#58]
Hi Zusammen,

ich erhalte seit Einbindung meiner Lüftungsanlage (was übrigens einwandfrei funktioniert hat) folgende Fehlermeldung:

`<html>
<body>

wolf.0 | 2021-12-25 01:13:46.306 | debug | incomingDevice: cwlDatapoint: 149Datapoint_name: Programmwahl CWLDatapoint_type: DPT_HVACModeData: 0620f080001504000000f006009500010095030103Length: 21Value:
-- | -- | -- | --
wolf.0 | 2021-12-25 01:13:46.305 | error | Can't parse DP : 149 - data: 0620f080001504000000f006009500010095030103 - length: 21

</body>
</html>`

Leider kann ich die Anzahl Zeichen nicht manuell ändern. Gibt es einen Workaround um den Fehler abzustellen bzw. im Programm zu beheben?

Danke und Gruß,

Claus

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by Apollon77** [comment]
Please try GitHub version
