### ISSUE TITLE
Add datapoint wolf.0.bm1.194

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#61]
Hi all,

I manually added datapoint wolf.0.bm1.194 (1xWarmwasserladung | 1x warm water) in order to automate a logic for saving energy.
Could you please add this datapoint into the adapter by default? Manually added works perfect but would be great if included by default.
I use it to store photovoltaic energy with raising the warm water temperature when the sun is shining for more than 15 min from 45 to 58 degrees. Therefore I use the datapoint to start the warming up process.

Thx and brgds,

Claus

**Comment by Apollon77** [comment]
The state shopuld be there ... at least on GitHub ... which version you use taht it is missed?
