### ISSUE TITLE
No objects created from WOLF adapter

### ISSUE THREAD

**Issue by JarlMorgennebel** [ioBroker/ioBroker.wolf#64]
Hej,

my ISM8i-Modul is configured to use DHCP and uses IP-address 192.168.1.158/24 ("LAN" Network).

<img width="767" alt="Bildschirmfoto 2022-04-24 um 16 44 25" src="https://user-images.githubusercontent.com/59556758/164982120-49fabffa-64c7-4862-bf1e-0c5f6b9050dc.png">

My IOBroker is configured at 192.168.3.30/24 and uses Port 12004 for WOLF ("SERVERLAN" network).

Between LAN- and SERVERLAN network an Opnsense firewall routes traffic. To allow traffic from ISM8i to IOBroker a very open rule is configured:

   Allow IPv4/Any Protocol, Any Port.   to  Host_IOBroker, Any Port

<img width="1262" alt="Bildschirmfoto 2022-04-24 um 16 46 50" src="https://user-images.githubusercontent.com/59556758/164982127-1d31cd92-102f-4ed0-881c-79f30cb18fce.png">

Connect from LAN any client to Wolf adapter on Port 12004 is working fine (tested with telnet):

<img width="576" alt="Bildschirmfoto 2022-04-24 um 16 49 21" src="https://user-images.githubusercontent.com/59556758/164982195-0b6ad484-86c4-4e86-940b-1801100659e5.png">

And IOBroker shows active connections from ISM8i on the Linux operating system level:

<img width="759" alt="Bildschirmfoto 2022-04-24 um 16 51 56" src="https://user-images.githubusercontent.com/59556758/164982338-e80f1732-43f1-4377-ac43-e50b12f7a8aa.png">

Wolf Adapter is configured but is not creating any objects:

<img width="1384" alt="Bildschirmfoto 2022-04-24 um 16 53 32" src="https://user-images.githubusercontent.com/59556758/164982399-5515f6d0-5ea3-4e44-a711-d3716d7b0c82.png">

I have restarted the Adapter and the Host. No changes.

What else can I test to get the Wolf adapter working again?

Thanks, -JM

**Comment by Apollon77** [comment]
What is configured in the "bind" setting of the adapter? In fact this would mean that no connection is done, OR that no data coming back after adapter is asking for them ...

You can install GitHub version and set the loglevekl of the instance to "debug" then you see if a connection comes in

**Comment by JarlMorgennebel** [comment]
Hej,

Thanks for the quick follow-up. 

The adapter is configured to use eth0 IP 192.168.3.30, Port 12004. Which works fine, as I can establish a connection using telnet to the Adaptor (TCP handshake is completed and data transferred)

<img width="676" alt="Bildschirmfoto 2022-04-24 um 17 30 26" src="https://user-images.githubusercontent.com/59556758/164984040-2fe3a58a-4c79-42b0-b27d-b87338b57d08.png">

I'll install the GitHub version and post a debug.

TY
.

**Comment by Apollon77** [comment]
Please check the other options for the bind setting ... and you really tried to connect from an other computer in the network? Not that this bind setting just allows local connections ... I would have expected a 0.0.0.0 or such

**Comment by JarlMorgennebel** [comment]
Interesting.

The GitHub installation works fine and Objects are created. But I do get a lot of warnings:

`


2022-04-24 17:34:08.046 | warn | State value to set for "wolf.0.sm1.195" has value "32768" greater than max "10000"
-- | -- | --
wolf.0 | 2022-04-24 17:34:07.191 | info | State value to set for "wolf.0.sm1.145" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:34:07.025 | info | State value to set for "wolf.0.sm1.144" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:34:06.844 | info | State value to set for "wolf.0.sm1.143" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:34:06.671 | info | State value to set for "wolf.0.sm1.142" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:34:06.491 | info | State value to set for "wolf.0.sm1.141" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:34:04.724 | warn | State value to set for "wolf.0.sm1.138" has value "-40" less than min "0"
wolf.0 | 2022-04-24 17:34:01.734 | warn | State "wolf.0.sm1.135" has no existing object, this might lead to an error in future versions
wolf.0 | 2022-04-24 17:34:01.551 | warn | State value to set for "wolf.0.mm1.120" has value "-40" less than min "0"
wolf.0 | 2022-04-24 17:34:01.380 | warn | State value to set for "wolf.0.mm1.119" has value "-40" less than min "0"
wolf.0 | 2022-04-24 17:34:01.220 | info | State value to set for "wolf.0.mm1.118" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:34:01.052 | info | State value to set for "wolf.0.mm1.117" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:34:00.719 | warn | State value to set for "wolf.0.mm1.115" has value "-40" less than min "0"
wolf.0 | 2022-04-24 17:34:00.561 | warn | State "wolf.0.mm1.114" has no existing object, this might lead to an error in future versions
wolf.0 | 2022-04-24 17:33:56.379 | info | State value to set for "wolf.0.bm1.64" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:56.377 | info | State value to set for "wolf.0.bm1.63" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:56.375 | info | State value to set for "wolf.0.bm1.62" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:56.316 | info | State value to set for "wolf.0.bm1.61" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:56.220 | info | State value to set for "wolf.0.bm1.61" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:56.218 | info | State value to set for "wolf.0.bm1.60" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:56.216 | info | State value to set for "wolf.0.bm1.59" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:51.796 | warn | State "wolf.0.bm1.53" has no existing object, this might lead to an error in future versions
wolf.0 | 2022-04-24 17:33:51.579 | info | State value to set for "wolf.0.hg1.12" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:51.482 | info | State value to set for "wolf.0.hg1.12" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:51.481 | info | State value to set for "wolf.0.hg1.11" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:51.479 | info | State value to set for "wolf.0.hg1.10" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:51.330 | info | State value to set for "wolf.0.hg1.9" has to be type "string" but received type "boolean"
wolf.0 | 2022-04-24 17:33:50.085 | warn | State "wolf.0.hg1.1" has no existing object, this might lead to an error in future versions
 

<br class="Apple-interchange-newline">
`

**Comment by Apollon77** [comment]
Interesting ... I changed nothing ... only added logs :-)

Can you please create a new issue for the errors of datatypes, seems there arer some wrong values :-(
