### ISSUE TITLE
Data points don´t get updated after updating to v1.4

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#68]
First thx for the update!

**Describe the bug**  
All data points are filled once when the adapter is started/restarted, but are not updated afterwards.
Strange thing is that log in debug mode shows constant updates from the adapter:
`<html>
<body>

source | time | debug | message
-- | -- | -- | --
wolf.0 | 2022-04-26 13:24:26.089 | debug | Data from 192.168.178.107:51304: 0620f080001704000000f006009c0001009c03030d1900
wolf.0 | 2022-04-26 13:23:17.947 | debug | Data from 192.178.148.107:51304: 0620f080001704000000f00600a2000100a20303101800
wolf.0 | 2022-04-26 13:23:17.798 | debug | Data from 192.178.148.107:51304: 0620f080001704000000f00600a1000100a103030d1800
wolf.0 | 2022-04-26 13:23:17.165 | debug | Data from 192.178.148.107:51304: 0620f080001704000000f006009d0001009d0303101800
wolf.0 | 2022-04-26 13:23:17.012 | debug | Data from 192.178.148.107:51304: 0620f080001704000000f006009c0001009c03030d1800
wolf.0 | 2022-04-26 13:22:19.692 | debug | Data from 192.178.148.107:51304: 0620f080001604000000f00600a5000100a5030203fc

</body>
</html>`

**To Reproduce**  
1. Start the adapter
2. Go to objects explorer
3. See timestamp / last changed date+time

**Expected behavior**  
Data points get updated constantly

**Screenshots & Logfiles**  
What specifically do you need?

**Versions:**  
 - Adapter version: 1.4
 - JS-Controller version:  4.0.21
 - Node version: 14.19.1
 - Operating system: Raspbian Buster

**Additional context**  
With the previous version 1.34 data points got updated constantly and reliably

**Comment by Claus1985** [comment]
ok nevermind.. it works as designed and updates all values. I was just to impatient.

**Comment by Apollon77** [comment]
I love issues that solve itself :-)
