### ISSUE TITLE
No datapoints created. Data connection is ok.

### ISSUE THREAD

**Issue by booleeny** [ioBroker/ioBroker.wolf#76]
**Describe the bug**  
I installed the adapter. I see that data is received from ISM8i. But the object list is still empty.
Any hints to get the adapter creating objects?
Therme:  **CSZ-2 14/300R + CWL-300  excellent**
[https://www.wolf.eu/shk-profi/gas-thermen/gasbrennwert-solar-zentrale-csz-2/](url)

_Plattform	linux
Betriebssystem	linux
Architektur	arm
CPUs	4
Modell	ARMv7 Processor rev 3 (v7l)
RAM	3.75 GB
System-Betriebszeit	49 T. 11:35:19
Node.js	v14.19.3
Anzahl der Adapter	497
NPM	6.14.17
Datenträgergröße	109.74 GB
freier Festplattenspeicher	100.01 GB
Betriebszeit	00:41:20
Aktive Instanzen	14
Weg	/opt/iobroker/
Hostname	raspberrypi_

![2022-05-19 09_58_06-Window](https://user-images.githubusercontent.com/19393195/169243422-b238e109-398f-4009-b41a-b0f711b00925.png)
![2022-05-19 09_59_17-Window](https://user-images.githubusercontent.com/19393195/169243448-98df8f88-6c5e-437f-8d47-d9f832cc6fc9.png)

**To Reproduce**  
1. Installed adapter
2. Activate available sensors
3. Observe objects for ~30min
4. No new objects created

I tried to reinstall the adapter and deleted all objects before installing the new one. Also restarted the therme a few times. But i guess it is a adapter problem as the data is coming and connection seems ok.

![2022-05-19 10_13_15-Window](https://user-images.githubusercontent.com/19393195/169245903-14c3e482-9aac-4930-b345-0cb61e85ad82.png)

**Expected behavior**  
- New objects created after ~20min

**Screenshots & Logfiles**  
**[iobroker.2022-05-19.log](https://github.com/ioBroker/ioBroker.wolf/files/8727523/iobroker.2022-05-19.log)**

![2022-05-19 10_11_55-Window](https://user-images.githubusercontent.com/19393195/169245685-e9e666d4-4a78-4b11-925f-8d755a0d06dc.png)
![2022-05-19 10_12_18-Window](https://user-images.githubusercontent.com/19393195/169245705-a6a01457-195a-469d-93b2-569772ef43dc.png)

**Versions:**  
 - Adapter version: 1.4.0
 - JS-Controller version: 4.0.23 
 - Node version: V14.19.3
 - NPM: 6.14.17
 - Operating system: linux raspberry, no docker

**Additional context**  
I used the fork from https://github.com/**Dark-Tower-Coder**/ioBroker.wolf before which was working fine. As all should be in line again after merging i gave this one a try again.

**Comment by Apollon77** [comment]
Please choose the 0.0.0.0 entry in iobroker as IP ... the newsest version has renamed that in UI because misleading. it is "Bind" ...

**Comment by booleeny** [comment]
Thank you for the reply. I deinstalled the adapter and installed it again. Resartet the raspberry. Physically restartet the heater. No success the objects are still not created, just the admin object is created. The connection seems ok as data is coming in if i check in debug mode.

`<html>
<body>


wolf.0 | 2022-05-19 12:00:50.603 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f0060038000100380302144c
-- | -- | -- | --
wolf.0 | 2022-05-19 12:00:50.411 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f00600370001003703020000
wolf.0 | 2022-05-19 12:00:50.251 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f00600360001003603020d37
wolf.0 | 2022-05-19 12:00:50.110 | debug | Data from 192.168.1.15:61737: 0620f080001504000000f006003500010035030100
wolf.0 | 2022-05-19 12:00:49.961 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f006000d0001000d030274ef
wolf.0 | 2022-05-19 12:00:49.801 | debug | Data from 192.168.1.15:61737: 0620f080001504000000f006000c0001000c030100
wolf.0 | 2022-05-19 12:00:49.798 | debug | Data from 192.168.1.15:61737: 0620f080001504000000f006000b0001000b030100
wolf.0 | 2022-05-19 12:00:49.796 | debug | Data from 192.168.1.15:61737: 0620f080001504000000f006000a0001000a030100
wolf.0 | 2022-05-19 12:00:49.637 | debug | Data from 192.168.1.15:61737: 0620f080001504000000f006000900010009030100
wolf.0 | 2022-05-19 12:00:49.476 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f00600080001000803020d37
wolf.0 | 2022-05-19 12:00:49.317 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f00600070001000703021686
wolf.0 | 2022-05-19 12:00:49.156 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f00600060001000603020d4b
wolf.0 | 2022-05-19 12:00:48.996 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f00600050001000503020000
wolf.0 | 2022-05-19 12:00:48.836 | debug | Data from 192.168.1.15:61737: 0620f080001604000000f00600040001000403020e4f
wolf.0 | 2022-05-19 12:00:48.686 | debug | Data from 192.168.1.15:61737: 0620f080001504000000f006000300010003030100
wolf.0 | 2022-05-19 12:00:48.526 | debug | Data from 192.168.1.15:61737: 0620f080001504000000f006000200010002030106
wolf.0 | 2022-05-19 12:00:48.374 | debug | Data from 192.168.1.15:61737: 0620f080001504000000f006000100010001030100
wolf.0 | 2022-05-19 12:00:42.635 | debug | Receive new connection from 192.168.1.15:61737, requesting GetAll
wolf.0 | 2022-05-19 12:00:39.175 | debug | Server listening on 0.0.0.0:12004
wolf.0 | 2022-05-19 12:00:39.073 | info | starting. Version 1.4.0 in /opt/iobroker/node_modules/iobroker.wolf, node: v14.19.3, js-controller: 4.0.23
wolf.0 | 2022-05-19 12:00:38.666 | debug | Plugin sentry Initialize Plugin (enabled=true)
wolf.0 | 2022-05-19 12:00:38.581 | debug | States connected to redis: 127.0.0.1:9000
wolf.0 | 2022-05-19 12:00:38.558 | debug | States create User PubSub Client
wolf.0 | 2022-05-19 12:00:38.556 | debug | States create System PubSub Client
wolf.0 | 2022-05-19 12:00:38.539 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
wolf.0 | 2022-05-19 12:00:38.505 | debug | Objects connected to redis: 127.0.0.1:9001
wolf.0 | 2022-05-19 12:00:38.495 | debug | Objects client initialize lua scripts
wolf.0 | 2022-05-19 12:00:38.413 | debug | Objects create User PubSub Client
wolf.0 | 2022-05-19 12:00:38.411 | debug | Objects create System PubSub Client
wolf.0 | 2022-05-19 12:00:38.408 | debug | Objects client ready ... initialize now
wolf.0 | 2022-05-19 12:00:38.345 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
wolf.0 | 2022-05-19 12:00:34.330 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
wolf.0 | 2022-05-19 12:00:34.326 | info | terminating
wolf.0 | 2022-05-19 12:00:33.822 | info | Got terminate signal TERMINATE_YOURSELF

</body>
</html>

![2022-05-19 11_39_51-Window](https://user-images.githubusercontent.com/19393195/169267234-7bf220fb-9d7d-4dd8-b228-e624704e5028.png)
![2022-05-19 11_40_50-Window](https://user-images.githubusercontent.com/19393195/169267291-767ce1e6-b65a-49a2-ab92-5c92fd32f2fc.png)

![2022-05-19 11_41_15-Window](https://user-images.githubusercontent.com/19393195/169267261-09ed6bdb-5f7f-4143-9c9c-69cdadb796d9.png)
.

**Comment by booleeny** [comment]
Ok i was able to fix the issue. I added *_t to all names in main.js
64  'hg1_t'
66  'hg2_t';
[...]
101 'hg1_t'
103 'hg2_t'
[...]
[main.js.txt](https://github.com/ioBroker/ioBroker.wolf/files/8729366/main.js.txt)

All objects filled instantly after restart of the adapter
![2022-05-19 15_11_14-objects - raspberrypi und 1 weitere Seite - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/19393195/169301523-9322b899-9d25-4c73-b720-1fcf2610d0a6.png)

**Comment by Apollon77** [comment]
Does anyone know ehen _t is needed and when not???

**Comment by booleeny** [comment]
> 
I guess its because of the html gui table created in ioBroker.wolf/admin/**index.html**? But i dont know about the relations. There is also a **hg2_n** which i did not adjust. Changing the variables in main.js are working for me.

Line
61
>     }
> 
>     #hg1_t-button > span.ui-selectmenu-text {
>         font-size: small;
>         padding: 4px;
>     }
> 

Line 234 ff
```
<input type="checkbox" class="checkbox" id="**hg1_t**"/><label for="hg1_t" class="translate">Auto</label>
            </td>
            <td class="translate">Name:</td>
            <td><input class="names" id="hg1_n" type="text"/></td>
        </tr>
        <tr>
            <td class="number">(2)</td>
            <td>
                <input type="checkbox" class="checkbox" id="**hg2_t**"/><label for="hg2_t" class="translate">Auto</label>
            </td>
            <td class="translate">Name:</td>
            <td><input class="names" id="hg2_n" type="text"/></td>
        </tr>
        <tr>
            <td class="number">(3)</td>
            <td>
                <input type="checkbox" class="checkbox" id="**hg3_t**"/><label for="hg3_t" class="translate">Auto</label>
            </td>
            <td class="translate">Name:</td>
            <td><input class="names" id="hg3_n" type="text"/></td>
        </tr>
```

**Comment by Apollon77** [comment]
Ok, now I got it ... could you please check the GitHub versionif it wouks "without your changes"?

**Comment by booleeny** [comment]
I deinstalled the adapter and removed /opt/iobroker/node_modules/iobroker.wolf. Installed latest from Git via developer mode. **All possible objects showed up.** Also all possible devices where activated (Auto) by default in the adapter settings which worked fine.
Thanks and can be merged and closed

**Comment by Apollon77** [comment]
Thank you, v1.5.0 will come
