### ISSUE TITLE
No Updated values with since 1.5

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#77]
**Describe the bug**  
Since updating to v 1.5 my values don´t get updated anymore.
v 1.4 works like a charm and downgrading brings back regular value updates
Only message I get in log is:

![image](https://user-images.githubusercontent.com/69499563/172924500-7982c508-b82a-4561-b42e-3869ceeea8d4.png)

Any idea what could be wrong?

**Comment by Apollon77** [comment]
Please install 1.5, go to the config, check and safe once

**Comment by Claus1985** [comment]
Tried 2 times, did not work. Do I have to delete the object tree?

**Comment by Apollon77** [comment]
Could be worth a try

**Comment by Claus1985** [comment]
Didn´t work.. any idea on what could be wrong? How can I get detailed debug messages?
I activated debug but it does only show the messages from original post..

Thx!

**Comment by Apollon77** [comment]
Where you actvated debug? You need to change the loglevel of the istance at "Instances" and active expert mode. then open the instance in the list and set the loglevel. Please also show your configuration

**Comment by Claus1985** [comment]
Debug log just shows data is beeing received but in object tree I don´t see any updates (all data there with timestamp after deleting the object tree and restarting the adapter):
![image](https://user-images.githubusercontent.com/69499563/174481034-396359f5-e39a-4ebc-b592-21d57ddd06dc.png)

I changed the "Warmwassersolltemperatur" directly on the device but the value is not updated in ioBroker.

**Comment by Claus1985** [comment]
ok forget about my comment.. It just took a few minutes in order to update the objects. Adapter works fine! 👍
