### ISSUE TITLE
Adapter legt die Datenpunkte für das Mischermodul nicht an.

### ISSUE THREAD

**Issue by Lollo79** [ioBroker/ioBroker.wolf#83]
ioB Log: 'wolf.0 | 2022-10-16 21:37:09.537 | debug | Ignore data for device type mm1_t because configured undefined'

Mir fehlen leider die Datenpunkte von 114 - 120 für das Mischermodul

 - Adapter version: 1.50
 - JS-Controller version:  4.0.23
 - Node version:  16.17.1
 - Operating system:  debian

Ich warte meist ein paar Monate bis ich einen Adapter ein Update gönne 
bin von 1.40 (alles funktioniert so wie es soll) jetzt auf 1.50 war eine Menge Arbeit alles wieder für die InfluxDB und auch die Scripte anzupassen jedoch fehlen mir jetzt die genannten Datenpunkte was sehr schade ist da man ja immer alles up to date halten will.

**Comment by Apollon77** [comment]
Please provide a debug log

**Comment by Lollo79** [comment]
Hi Appolon77, 

ich habe es hinbekommen, hab nochmal  V1.40 installiert dabei wird das mm1 ohne _t wieder angelegt und hab die Struktur über die Klon Funktion mit dem _t geklont V1.50 drüber und alles läuft wie es soll.

**Comment by Apollon77** [comment]
Schaue es mir trotzdem gern nochmal an, daher reopen :-) ABer danke für Feedback

**Comment by redtom13** [comment]
Selbes Problem hier. MM Datenpunkte werden in der 1.50 nicht angelegt. Nach Installation von 1.40 gar keine Datenpunkte. 

Dann nach Upate der 1.40 auf 1.50 über Ui alle Datenpunkte da, inkl. Mischer MM.

**Comment by Apollon77** [comment]
Bitte mal Konfig speichern ind er 1.5.0 dann startet adapter neu ... dann nicht da? Dann Debug log bitte posten

**Comment by Apollon77** [comment]
Please Test GitHub version and provide feedback. Please also check that it is still ok after saving the config once

**Comment by Apollon77** [comment]
*ping*, Anyone available to test the fix?
