### ISSUE TITLE
encoding for DPT10

### ISSUE THREAD

**Issue by gkressel** [ioBroker/ioBroker.wolf#89]
Hey guys,

thanks for working in this adapter.
I want to ask if it's possible to implement an encoding for DPT10 (timeofDay).
For my CWL-2 I need to set the end time for activatiing the power mode. Based on the documentation from wolf it's mandatory to set all 3 parameters (DP153, 155 and 157) to activate. 

When i try to set the values i got the message that the encoding is not supported.
![grafik](https://user-images.githubusercontent.com/88251998/200832571-12585ea6-77fb-475b-94b6-13165d96d8f8.png)

If the endtime is already larger than the current timestamp, i can activate the mode.

Thanks in advance!

Best regards,
Gunnar

**Comment by Apollon77** [comment]
Does anyone know the definiton/spefication?

**Comment by Apollon77** [comment]
Thank you, I think the more interesting question is how to allow users to set this. Could be setting a date object as the "encoded" one, but then we only take out weekday and time. I can give it a try

**Comment by gkressel** [comment]
as in the wolf documentation is mentioned, they will only consider the hour and minute from this DPT. Therefore it should be fine to use the same logic as in the decoding part. If "time to set" > now --> use today else tomorrow.
The use case where these DPTs are needed is to enable the building protection or the power mode. In both cases it's mandatory to set the start and end times as well as the dates represented by DPT 154 - 157 and the switch DPT 153.

**Comment by Apollon77** [comment]
Ok, then here you go ... Please try GitHub version ...
