### ISSUE TITLE
Value range of datapoint 165 fresh air temperatur "Frischluft" is not sufficient (warning when < 0)

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#91]
Value range of datapoint 165 fresh air temperatur "Frischluft" is not sufficient. 
I get the following warning if temperature falls below 0: 
`State value to set for "wolf.0.cwl_t.165" has value "-1.3" less than min "0"`

Could you change that in the next version?

Thx for your work and for the adapter!

**Versions:**  
 - Adapter version: 1.50

**Comment by gkressel** [comment]
same issue with the DP164:
wolf.0 | 2022-12-12 05:07:53.695 | warn | State value to set for "wolf.0.cwl_t.164" has value "-0.2" less than min "0"

**Comment by Apollon77** [comment]
Please Test GitHub version and provide feedback.

**Comment by Claus1985** [comment]
Bekomme die Meldung immer noch:
`State value to set for "wolf.0.cwl_t.165" has value "-0.1" less than min "0" `

**Comment by Apollon77** [comment]
Dann bitte dss Objekt mallöschen ... dann adapter neu starten und es sollte neu angelegt werden. Dann immer noch?

**Comment by Claus1985** [comment]
Funktioniert, allerdings kam nun folgende Meldung:
`Can't parse DP : 149 - data: 0620f080001504000000f0060095000100950301c2 - length: 21`

**Comment by Apollon77** [comment]
Jetzt aber bitte nicht themen mischen. Kam es eingmalig oder öfter? Sieht nach irgendwie komischen Daten aus. Wenn es bleibt nochmal Github version und nochmal laufen lassen und neue Fehlemeldung in neues Issue

**Comment by Claus1985** [comment]
Kam bisher nur einmal. Ich mach das Ticket zu da der Change funktioniert. Sollte der Fehler nochmal auftauchen mach ich ein separates Ticket auf. Danke fürs schnelle fixen!! :-)
